background            #111111
foreground            #ffffff
cursor                #f2f2f2
selection_background  #1f1f1f
selection_foreground  #ffffff

color0  #0a0a0a
color1  #e6e6e6
color2  #888888
color3  #cccccc
color4  #f2f2f2
color5  #dddddd
color6  #999999
color7  #777777
