background {
    monitor =
    path = /home/zkr/.config/hypr/current_wallpaper
    
    blur_passes = 3 
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(180, 190, 254) # Lavender
    inner_color = rgb(30, 30, 46)     # Base
    font_color = rgb(205, 214, 244)  # Text
    fade_on_empty = true
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(205, 214, 244)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
